### ISSUE TITLE
{"error":"sequence item 0: expected str instance, Line found"}

### ISSUE THREAD

**Issue by loghyr** [ietf-tools/xml2rfc#1127]
### Describe the issue

To reproduce:

git clone git@github.com:loghyr/flexfilesv2.git
cd flexfilesv2
make

Submit resulting file draft-haynes-nfsv4-flexfiles-v2-00.xml  to https://author-tools.ietf.org/idnits

Or submit the following: (might have to rename to .xml)
[draft-haynes-nfsv4-flexfiles-v2-00.txt](https://github.com/user-attachments/files/15813948/draft-haynes-nfsv4-flexfiles-v2-00.txt)

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by cabo** [comment]
The full error message is:

```
draft-haynes-nfsv4-flexfiles-v2-00.v2v3.xml(312): Warning: Was asked to render a deprecated element: <list>
    c: '<Element list at 0x10ab6c320>'
Traceback (most recent call last):
[…]
  File "/opt/homebrew/lib/python3.11/site-packages/xml2rfc/writers/text.py", line 371, in render
    res = func(e, width, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/xml2rfc/writers/text.py", line 616, in default_renderer
    ctext = "\n\n".join(ctext)
            ^^^^^^^^^^^^^^^^^^
TypeError: sequence item 0: expected str instance, Line found

*** xml2rfc failed, status 1 (possibly try with -r)
```

Workaround:

Delete line 17 of the XML file:

```
 version="3"
```

Now:

```
xml2rfc draft-haynes-nfsv4-flexfiles.xml
```

…works.

For a more compliant solution.

```
xml2rfc --v2v3 draft-haynes-nfsv4-flexfiles.xml
xml2rfc draft-haynes-nfsv4-flexfiles-v2v3.xml
```

(You can continue using the -v2v3 result as your XML file, or stick with simply using the XML file with the deleted `version=“3”`.)

Grüße, Carsten
