### ISSUE TITLE
crash during PDF generation

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/xml2rfc#484]
`type_defect`   |    by arusso@amsl.com

___

RFC-to-be 8704 (draft-ietf-opsec-urpf-improvements-04) - PDF generation crashes. Traceback below.

input: https://www.rfc-editor.org/authors/rfc8704.xml

```
Traceback (most recent call last):
  File "/usr/bin/xml2rfc", line 11, in <module>
    load_entry_point('xml2rfc==2.37.3', 'console_scripts', 'xml2rfc')()
  File "/usr/lib/python2.7/site-packages/xml2rfc/run.py", line 620, in main
    writer.write(filename)
  File "/usr/lib/python2.7/site-packages/xml2rfc/writers/pdf.py", line 100, in write
    pdf = self.pdf()
  File "/usr/lib/python2.7/site-packages/xml2rfc/writers/pdf.py", line 89, in pdf
    pdf = writer.write_pdf(None, stylesheets=[ css, page_css ])
  File "/usr/lib/python2.7/site-packages/weasyprint/__init__.py", line 182, in write_pdf
    font_config=font_config).write_pdf(
  File "/usr/lib/python2.7/site-packages/weasyprint/__init__.py", line 143, in render
    font_config)
  File "/usr/lib/python2.7/site-packages/weasyprint/document.py", line 326, in _render
    [Page(p, enable_hinting) for p in page_boxes],
  File "/usr/lib/python2.7/site-packages/weasyprint/layout/__init__.py", line 55, in layout_document
    context, root_box, html, cascaded_styles, computed_styles))
  File "/usr/lib/python2.7/site-packages/weasyprint/layout/pages.py", line 599, in make_all_pages
    page_type, cascaded_styles, computed_styles, html)
  File "/usr/lib/python2.7/site-packages/weasyprint/layout/pages.py", line 562, in set_page_type_computed_styles
    base_url=html.base_url)
  File "/usr/lib/python2.7/site-packages/weasyprint/css/__init__.py", line 525, in set_computed_styles
    element, cascaded, parent_style, pseudo_type, root_style, base_url)
  File "/usr/lib/python2.7/site-packages/weasyprint/css/__init__.py", line 570, in computed_from_cascaded
    value = parent_style[name]
KeyboardInterrupt
```

___
_Issue migrated from trac:484 at 2022-02-08 07:05:34 +0000_

**Comment by kesara** [comment]
@alicerusso, closing this as OBE.
