### ISSUE TITLE
text rendering of table leads to crash

### ISSUE THREAD

**Issue by alicerusso** [ietf-tools/xml2rfc#740]
complex table renders ok in HTML and PDF, but crashes when making text.

When using ```<table>``` in XML:
- https://www.rfc-editor.org/v3test/draft-zia-route-table2.xml
- https://www.rfc-editor.org/v3test/draft-zia-route-table2.html 
- https://www.rfc-editor.org/v3test/draft-zia-route-table2.pdf 
(orig table: https://datatracker.ietf.org/doc/html/draft-zia-route-06#section-10)

TXT: crashes w/ Traceback as follows.
```Traceback (most recent call last):
  File "/usr/bin/xml2rfc", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.6/site-packages/xml2rfc/run.py", line 742, in main
    writer.write(filename)
  File "/usr/lib/python3.6/site-packages/xml2rfc/writers/text.py", line 343, in write
    text = self.process()
  File "/usr/lib/python3.6/site-packages/xml2rfc/writers/text.py", line 301, in process
    lines = self.render(self.root, width=72, joiners=joiners)
  File "/usr/lib/python3.6/site-packages/xml2rfc/writers/text.py", line 367, in render
    res = func(e, width, **kwargs)
  File "/usr/lib/python3.6/site-packages/xml2rfc/writers/text.py", line 3054, in render_rfc
    lines = self.ljoin(lines, c, width, **kwargs)
  File "/usr/lib/python3.6/site-packages/xml2rfc/writers/text.py", line 554, in ljoin
    res = mklines(self.render(e, width, **kwargs), e)
  File "/usr/lib/python3.6/site-packages/xml2rfc/writers/text.py", line 367, in render
    res = func(e, width, **kwargs)
  File "/usr/lib/python3.6/site-packages/xml2rfc/writers/text.py", line 2232, in render_middle
    lines = self.ljoin(lines, c, width, **kwargs)
  File "/usr/lib/python3.6/site-packages/xml2rfc/writers/text.py", line 554, in ljoin
    res = mklines(self.render(e, width, **kwargs), e)
  File "/usr/lib/python3.6/site-packages/xml2rfc/writers/text.py", line 367, in render
    res = func(e, width, **kwargs)
  File "/usr/lib/python3.6/site-packages/xml2rfc/writers/text.py", line 3325, in render_section
    lines = self.ljoin(lines, c, width, **kwargs)
  File "/usr/lib/python3.6/site-packages/xml2rfc/writers/text.py", line 554, in ljoin
    res = mklines(self.render(e, width, **kwargs), e)
  File "/usr/lib/python3.6/site-packages/xml2rfc/writers/text.py", line 367, in render
    res = func(e, width, **kwargs)
  File "/usr/lib/python3.6/site-packages/xml2rfc/writers/text.py", line 4250, in render_table
    lines = self.build_table(e, width, **kwargs)
  File "/usr/lib/python3.6/site-packages/xml2rfc/writers/text.py", line 4143, in build_table
    k, l = cell.origin
AttributeError: 'Cell' object has no attribute 'origin'
```

**Comment by kesara** [comment]
This seems to happen because table cells are unbalanced. Some raws are not fully covering the required number of cells.

With the [proposed change](#801), `xml2rfc` would die with the following error rather than crashing.
```
draft-zia-route-table2.xml(33): Error: Inconsistent table width: Found different row lengths in this table
Unable to complete processing drafts/draft-zia-route-table2.xml
```

I will look into improving this error message to give more context.

**Comment by cabo** [comment]
I cannot find anything in RFC 7991 that would require that table rows are of the same length.
So I don't know why this is an error.
(Throwing a "not implemented" message certainly is better than crashing, but it seems to me there is still work to be done after that PR is merged.)

**Comment by alicerusso** [comment]
Here's another example of this issue - Table 1 renders ok in HTML and PDF, but crashes when making text. 
    https://www.rfc-editor.org/v3test/draft-ietf-cats-usecases-requirements-14-table1.xml
    https://www.rfc-editor.org/v3test/draft-ietf-cats-usecases-requirements-14-table1.html
    https://www.rfc-editor.org/v3test/draft-ietf-cats-usecases-requirements-14-table1.pdf
   (Original: https://www.ietf.org/archive/id/draft-ietf-cats-usecases-requirements-14.html#figure-6 (it was  a `<figure>` not a `<table>`))

(Side note: One workaround is to put "Requirements" into a single row bc the issue seems to be with rowspan="2" - in other words, this file generates text without crashing:
https://www.rfc-editor.org/v3test/draft-ietf-cats-usecases-requirements-14_alt_Table1.xml
https://www.rfc-editor.org/v3test/draft-ietf-cats-usecases-requirements-14_alt_Table1.txt )

xml2rfc --text crashes with Traceback as follows.
```
Traceback (most recent call last):
  File "/usr/local/bin/xml2rfc", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/xml2rfc/run.py", line 736, in main
    writer.write(filename)
  File "/usr/local/lib/python3.9/site-packages/xml2rfc/writers/text.py", line 340, in write
    text = self.process()
  File "/usr/local/lib/python3.9/site-packages/xml2rfc/writers/text.py", line 304, in process
    lines = self.render(self.root, width=MAX_WIDTH, joiners=joiners)
  File "/usr/local/lib/python3.9/site-packages/xml2rfc/writers/text.py", line 364, in render
    res = func(e, width, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/xml2rfc/writers/text.py", line 3083, in render_rfc
    lines = self.ljoin(lines, c, width, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/xml2rfc/writers/text.py", line 553, in ljoin
    res = mklines(self.render(e, width, **kwargs), e)
  File "/usr/local/lib/python3.9/site-packages/xml2rfc/writers/text.py", line 364, in render
    res = func(e, width, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/xml2rfc/writers/text.py", line 2241, in render_middle
    lines = self.ljoin(lines, c, width, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/xml2rfc/writers/text.py", line 553, in ljoin
    res = mklines(self.render(e, width, **kwargs), e)
  File "/usr/local/lib/python3.9/site-packages/xml2rfc/writers/text.py", line 364, in render
    res = func(e, width, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/xml2rfc/writers/text.py", line 3354, in render_section
    lines = self.ljoin(lines, c, width, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/xml2rfc/writers/text.py", line 553, in ljoin
    res = mklines(self.render(e, width, **kwargs), e)
  File "/usr/local/lib/python3.9/site-packages/xml2rfc/writers/text.py", line 364, in render
    res = func(e, width, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/xml2rfc/writers/text.py", line 3354, in render_section
    lines = self.ljoin(lines, c, width, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/xml2rfc/writers/text.py", line 553, in ljoin
    res = mklines(self.render(e, width, **kwargs), e)
  File "/usr/local/lib/python3.9/site-packages/xml2rfc/writers/text.py", line 364, in render
    res = func(e, width, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/xml2rfc/writers/text.py", line 4280, in render_table
    lines = self.build_table(e, width, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/xml2rfc/writers/text.py", line 4250, in build_table
    lines[-1] = Line(''.join(merge_border(prev_bottom_border_line.text[c], line.text[c]) for c in range(len(line.text))), line.elem)
  File "/usr/local/lib/python3.9/site-packages/xml2rfc/writers/text.py", line 4250, in <genexpr>
    lines[-1] = Line(''.join(merge_border(prev_bottom_border_line.text[c], line.text[c]) for c in range(len(line.text))), line.elem)
IndexError: string index out of range
```

**Comment by kesara** [comment]
@alicerusso, https://github.com/ietf-tools/xml2rfc/issues/740#issuecomment-3850394202 seems like a different issue.

Looks like if a `th` or `td` element have both `colspan` and `rowspan` set to a value `> 1`, `xml2rfc` fails to generate text.
For example any XML with `<td colspan="2" rowspan="2>` or `<th colspan="2" rowspan="2>` would generate and error.

I searched at my RFC and I-D collection and couldn't find any XML documents that had that matched above criteria (`//td[@colspan > 1 and @rowspan > 1] | //th[@colspan > 1 and @rowspan > 1]`).
