### ISSUE TITLE
Tests fail with Weasyprint 57.0

### ISSUE THREAD

**Issue by kitterma** [ietf-tools/xml2rfc#921]
### Describe the issue

Given you pinned the Weasyprint version to <57.0, I know this is known, but I don't see an open issue for it.  Pinning to a lower version isn't a viable solution for downstream distributors, so this does need to be fixed:

```======================================================================
ERROR: setUpClass (__main__.PdfWriterTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/autopkgtest-lxc.48kx6p_4/downtmp/build.obL/src/xxx/test.py", line 495, in setUpClass
    cls.elements_pdfxml = xmldoc(None, bytes=elements_pdfdoc)
  File "/usr/lib/python3/dist-packages/xml2rfc/walkpdf.py", line 96, in xmldoc
    return lxml.etree.fromstring(text)
  File "src/lxml/etree.pyx", line 3254, in lxml.etree.fromstring
  File "src/lxml/parser.pxi", line 1913, in lxml.etree._parseMemoryDocument
  File "src/lxml/parser.pxi", line 1793, in lxml.etree._parseDoc
  File "src/lxml/parser.pxi", line 1082, in lxml.etree._BaseParser._parseUnicodeDoc
  File "src/lxml/parser.pxi", line 615, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 725, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 654, in lxml.etree._raiseParseError
  File "<string>", line 14199
lxml.etree.XMLSyntaxError: PCDATA invalid Char value 23, line 14199, column 11

----------------------------------------------------------------------
Ran 42 tests in 21.851s

FAILED (errors=1)```

Full test log is available at https://ci.debian.net/data/autopkgtest/testing/amd64/x/xml2rfc/27394437/log.gz

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by kitterma** [comment]
Confirmed to be a Weasyprint issue fixed in https://github.com/Kozea/WeasyPrint/commit/71e9e257ccc7780f3c4e04893b11210bd06ad626 - closing.
